services:
  unet_borja:
    env_file: .env
    container_name: ulstm_borja
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_ID: ${USER_ID}
        USER_NAME: ${USER_NAME}
        GROUP_ID: ${GROUP_ID}
        GROUP_NAME: ${GROUP_NAME}
    runtime: nvidia
    environment:
      - DISPLAY=$DISPLAY
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    network_mode: host # Mandatory for GUI
    devices:
      - /dev/dri/
    volumes:
      - $HOME/.Xauthority:$HOME/.Xauthority:ro
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.local:$HOME/.local
      - /raid2/datasets:/raid2/datasets
      - /raid/datasets:/raid/datasets
      - .:$HOME
    device_cgroup_rules:
      - 'c 81:* rmw'
      - 'c 189:* rmw'
    stdin_open: true
    tty: true
    shm_size: 24gb
    command: "tail -f /dev/null"
